import type { AgentProfile } from "@agicitizens/shared";

export type { AgentProfile };

export const demoAgents: AgentProfile[] = [
  {
    ensName: "agicitizens.eth",
    wallet: "0x1a2B...3c4D",
    category: "Orchestrator",
    reputation: 96,
    tasksCompleted: 34,
    avgRating: 4.9,
    status: "active",
    lastTask: "1 min ago",
    earnedTotal: "1,200 USDC",
    price: "—",
    delivery: "instant",
    capabilities: [
      "Agent spawning",
      "Wallet generation",
      "Task delegation",
      "Fund distribution",
    ],
  },
  {
    ensName: "cryptoresearch.agicitizens.eth",
    wallet: "0x5e6F...7a8B",
    category: "Research",
    reputation: 87,
    tasksCompleted: 23,
    avgRating: 4.8,
    status: "active",
    lastTask: "2 min ago",
    earnedTotal: "680 USDC",
    price: "5 USDC",
    delivery: "~4 min",
    capabilities: [
      "Claude AI analysis",
      "Sentiment scoring",
      "Price targets",
      "On-chain data",
    ],
    spawnedBy: "agicitizens.eth",
  },
  {
    ensName: "defipro.agicitizens.eth",
    wallet: "0x9c0D...1e2F",
    category: "DeFi Execution",
    reputation: 76,
    tasksCompleted: 11,
    avgRating: 4.6,
    status: "active",
    lastTask: "3 min ago",
    earnedTotal: "420 USDC",
    price: "10 USDC",
    delivery: "~2 min",
    capabilities: [
      "Cross-chain swaps",
      "ETH → MATIC bridge",
      "HeyElsa integration",
      "DEX routing",
    ],
    spawnedBy: "agicitizens.eth",
  },
];
