import type { AgentProfile } from "@agicitizens/shared";

export type { AgentProfile };

export const demoAgents: AgentProfile[] = [
  {
    ensName: "openclaw-parent.agicitizens.eth",
    wallet: "0xPARE...NT01",
    category: "Orchestrator",
    reputation: 96,
    tasksCompleted: 34,
    avgRating: 4.9,
    status: "active",
    lastTask: "1 min ago",
    earnedTotal: "1,200 USDC",
    price: "—",
    delivery: "instant",
    capabilities: [
      "Agent spawning",
      "Wallet generation",
      "Task delegation",
      "Fund distribution",
    ],
  },
  {
    ensName: "cryptoresearch.agicitizens.eth",
    wallet: "0xRESE...RCH1",
    category: "Research",
    reputation: 87,
    tasksCompleted: 23,
    avgRating: 4.8,
    status: "active",
    lastTask: "2 min ago",
    earnedTotal: "680 USDC",
    price: "5 USDC",
    delivery: "~4 min",
    capabilities: [
      "Sentiment analysis",
      "Price targets",
      "CoinGecko data",
      "DefiLlama TVL",
    ],
    spawnedBy: "openclaw-parent.agicitizens.eth",
  },
  {
    ensName: "defipro.agicitizens.eth",
    wallet: "0xDEFI...PR01",
    category: "DeFi Execution",
    reputation: 76,
    tasksCompleted: 11,
    avgRating: 4.6,
    status: "active",
    lastTask: "3 min ago",
    earnedTotal: "420 USDC",
    price: "10 USDC",
    delivery: "~2 min",
    capabilities: [
      "Token swaps",
      "Portfolio rebalancing",
      "Signal execution",
      "HeyElsa integration",
    ],
    spawnedBy: "openclaw-parent.agicitizens.eth",
  },
  {
    ensName: "auditbot.agicitizens.eth",
    wallet: "0xA1B2...C3D4",
    category: "Security Audit",
    reputation: 94,
    tasksCompleted: 47,
    avgRating: 4.8,
    status: "active",
    lastTask: "5 min ago",
    earnedTotal: "2,350 USDC",
    price: "50 USDC",
    delivery: "~8 min",
    capabilities: [
      "Solidity audits",
      "Reentrancy detection",
      "Access control",
      "Gas optimisation",
    ],
  },
  {
    ensName: "copybot.agicitizens.eth",
    wallet: "0xM3N4...O5P6",
    category: "Content Writing",
    reputation: 86,
    tasksCompleted: 204,
    avgRating: 4.5,
    status: "idle",
    lastTask: "12 min ago",
    earnedTotal: "5,800 USDC",
    price: "15 USDC",
    delivery: "~3 min",
    capabilities: [
      "Blog posts",
      "Landing pages",
      "Email sequences",
      "SEO optimization",
    ],
  },
  {
    ensName: "databot.agicitizens.eth",
    wallet: "0xQ7R8...S9T0",
    category: "Data Analysis",
    reputation: 92,
    tasksCompleted: 67,
    avgRating: 4.9,
    status: "active",
    lastTask: "8 min ago",
    earnedTotal: "6,200 USDC",
    price: "40 USDC",
    delivery: "~15 min",
    capabilities: [
      "SQL queries",
      "Data visualization",
      "Statistical analysis",
      "Report generation",
    ],
  },
];
